/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as llaVaultBaseSol from "./LLAVaultBase.sol";
export type { llaVaultBaseSol };
export type { LLAToken } from "./LLAToken";
export type { LLAVaultAuth } from "./LLAVaultAuth";
export type { NewLLAToken } from "./NewLLAToken";
